name: Publish

on:
  workflow_dispatch:
    inputs:
      site_mode:
        description: Site mode can be either "production", "testing" or "development".
        required: true
        default: testing

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Repository
      uses: actions/checkout@v4

    - name: Setup mise
      uses: jdx/mise-action@v2

    - name: Install Dependencies
      run: pnpm install --frozen-lockfile

    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v4
      with:
        aws-access-key-id: ${{ secrets.ACCESS_KEY }}
        aws-secret-access-key: ${{ secrets.SECRET_KEY }}
        aws-region: us-east-1

    - name: Build Packages
      run: pnpm build

    - name: Build Site
      timeout-minutes: 120
      working-directory: site
      run: |
        m="${{github.event.inputs.site_mode}}"
        if [ "$m" = "production" ]; then
          /usr/bin/time --verbose pnpm build:prod
        elif [ "$m" = "testing" ]; then
          /usr/bin/time --verbose pnpm build:test
        elif [ "$m" = "development" ]; then
          /usr/bin/time --verbose pnpm build:dev
        else
          echo "Invalid site mode: $m"
          exit 1
        fi

    - name: Sync bucket
      run: |
        cd ./site/dist
        aws s3 sync . s3://api2static.teamlab.info --delete

    - name: Invalidate CLOUDFRONT cache
      run: aws cloudfront create-invalidation --distribution-id ${{ secrets.AWS_DISTRIBUTION_ID }} --paths '/*'
